### ISSUE TITLE
Add X to the list

### ISSUE THREAD

**Issue by Michael-Paragonn** [verbb/social-share#3]
### What are you trying to do?

My client wants to replace the venerable Twitter icons with X already. 🤷 

### What's your proposed solution?

Add X to the list of providers.

### Additional context

End of an era... * le sigh *

**Comment by engram-design** [comment]
Yeah, I was _kinda_ hoping that it wouldn't be a permanent thing haha! Added in [1.0.3](https://github.com/verbb/social-share/releases/tag/1.0.3)

**Comment by Michael-Paragonn** [comment]
Ch-ch-ch-changes! 🎶 🥴 Thanks, dude!
