### ISSUE TITLE
`renderShareButton` does not output the `data-url` attribute on the generated link element

### ISSUE THREAD

**Issue by kevincote** [verbb/social-share#6]
### Describe the bug

When using the helper `craft.socialShare.renderShareButton('facebook')` with the default configuration (so `useModalForShare` is true, there is no `data-url=[...]` attribute attached to the `<a>` tag, therefore the share functionality does not work.

### Steps to reproduce

1. Put `{{ craft.socialShare.renderShareButton('facebook') }}` anywhere on the page.
2. The generated tag does not include the `data-url` attribute.

### Craft CMS version

5.2.0

### Plugin version

2.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/social-share:"dev-craft-5 as 2.0.1"`.

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/social-share/releases/tag/2.0.2)
