### ISSUE TITLE
PrintProvider doesn't work.

### ISSUE THREAD

**Issue by jpwdesigns** [verbb/social-share#7]
### Describe the bug

When using the print provider to create a print button for printing page, i'm expecting to see onclick="window.print()" instead I see the following:

`<a class="print-share-btn" href="javascript:void();" aria-label="PrintProvider" onclick="window.open(this.dataset.url, &quot;ss_share_dialog&quot;, &quot;width=626,height=436&quot;);" data-url="?onclick=window.print%28%29%3B#" style="--brand-color: #d34836;">...</a>`

The onclick needs to be doing the window.print() instead of referencing a window.open().

### Steps to reproduce

1. `{{ craft.socialShare.renderShareButton('print') }}`

### Craft CMS version

5.4.4

### Plugin version

2.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/social-share/releases/tag/2.0.3)
